name: Deploy to Railway

on:
  push:
    branches: [main]

jobs:
  deploy-backend:
    name: Deploy Backend to Railway
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Install Railway CLI
        run: npm i -g @railway/cli
        
      - name: Deploy to Railway
        working-directory: ./backend
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
  
  deploy-frontend:
    name: Deploy Frontend to Railway
    runs-on: ubuntu-latest
    needs: deploy-backend
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Install Railway CLI
        run: npm i -g @railway/cli
        
      - name: Deploy to Railway
        working-directory: ./frontend
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }} 